#!/bin/bash
# ============================================================================
# TRIBE JURIS KIT — STEP 07 — PERSONALIZED LAUNCHER GENERATOR
# ============================================================================
# Generates a personalized boot script for your engine — modeled after
# RAZOR's launch_van_zile.sh. The generated script verifies your three
# server-side minds come up cleanly every time you log in.
#
# What this script does:
#   1. Asks for your engine name (interactive prompt)
#   2. Reads the external drive path saved in Step 02 (for Ollama models)
#   3. Generates two files in ~/Documents/:
#        launch_[engine].sh         — the actual boot logic (3-stage)
#        [Engine]Launcher.command   — Login Item wrapper (opens Terminal)
#   4. Includes binary store backup rotation (5 most recent kept)
#   5. Prints instructions to add [Engine]Launcher.command as a Login Item
#
# Prerequisites: Steps 02-04 complete (Ollama, AgentMemory, AnythingLLM all
#                installed and configured)
#
# Run:
#   bash ~/Documents/TRIBE_JURIS_KIT/07_personalized_launcher.sh
# ============================================================================

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}  ${BOLD}TRIBE JURIS KIT — STEP 07 — LAUNCHER GENERATOR${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}  Generates your personalized boot script             ${CYAN}║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

# --------------------------------------------------------------------------
# 1. ENGINE NAME
# --------------------------------------------------------------------------
echo -e "${BOLD}[1/4] Engine name${NC}"
echo -e "  ${CYAN}Use the same engine name you picked in Step 05.${NC}"
echo -e "  ${CYAN}Examples: Aurora, Vortex, Bastion, Sentinel, Glacier${NC}"
echo ""
printf "  Enter your engine name (single word, no spaces): "
read ENGINE_NAME

if [ -z "$ENGINE_NAME" ]; then
    echo -e "  ${RED}✗ No engine name given. Aborting.${NC}"
    exit 1
fi

# Sanitize for use as filename / variable
ENGINE_LOWER=$(echo "$ENGINE_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_')
ENGINE_TITLE=$(echo "$ENGINE_NAME" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')

if [ -z "$ENGINE_LOWER" ]; then
    echo -e "  ${RED}✗ Engine name contained no valid characters. Aborting.${NC}"
    exit 1
fi
echo -e "  ${GREEN}✓ Engine name: $ENGINE_TITLE (lowercase: $ENGINE_LOWER)${NC}"
echo ""

# --------------------------------------------------------------------------
# 2. EXTERNAL DRIVE PATH (Ollama models)
# --------------------------------------------------------------------------
echo -e "${BOLD}[2/4] Ollama models path${NC}"
if [ -f ~/.tribe_juris_kit_ollama_path ]; then
    OLLAMA_PATH=$(cat ~/.tribe_juris_kit_ollama_path)
    echo -e "  ${GREEN}✓ Reading from Step 02: $OLLAMA_PATH${NC}"
else
    echo -e "  ${YELLOW}⚠ Step 02 didn't save a path. Using default.${NC}"
    OLLAMA_PATH="$HOME/.ollama/models"
fi
echo ""

# --------------------------------------------------------------------------
# 3. GENERATE launch_[engine].sh
# --------------------------------------------------------------------------
echo -e "${BOLD}[3/4] Generating launch script${NC}"

LAUNCH_FILE="$HOME/Documents/launch_${ENGINE_LOWER}.sh"
WRAPPER_FILE="$HOME/Documents/${ENGINE_TITLE}Launcher.command"

cat > "$LAUNCH_FILE" <<EOF
#!/bin/bash
# ============================================================================
# ${ENGINE_TITLE^^} — SYSTEM LAUNCH SCRIPT
# ============================================================================
# Runs automatically at login via ${ENGINE_TITLE}Launcher.command (Login Item).
# Modeled after JURIS Razor Jurisprudence Engine.
#
# Launch order:
#   1. Ollama (LEAN — just nomic-embed-text for AgentMemory's embeddings)
#   2. AnythingLLM (JURIS) — WAIT ONLY — launched by macOS Login Item
#   3. AgentMemory (MEMORY — uses Claude API + Ollama /v1 embeddings)
#
# Generated by TRIBE JURIS KIT Step 07 on \$(date +%Y-%m-%d)
# ============================================================================

# NOTE: Do NOT use set -e — a timeout in one service must not kill the
# entire boot sequence. Each section handles its own errors gracefully.

GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
RED='\\033[0;31m'
CYAN='\\033[0;36m'
NC='\\033[0m'
BOLD='\\033[1m'

# Ollama models live on the external drive picked in Step 02
export OLLAMA_MODELS="${OLLAMA_PATH}"

echo ""
echo -e "\${CYAN}╔══════════════════════════════════════════════════════╗\${NC}"
echo -e "\${CYAN}║\${NC}  \${BOLD}${ENGINE_TITLE^^} — SYSTEM LAUNCH\${NC}"
echo -e "\${CYAN}║\${NC}  Tribe Stack: Ollama → JURIS → MEMORY → Cowork"
echo -e "\${CYAN}║\${NC}  Modeled after JURIS Razor Jurisprudence Engine"
echo -e "\${CYAN}╚══════════════════════════════════════════════════════╝\${NC}"
echo ""

# --------------------------------------------------------------------------
# HELPER
# --------------------------------------------------------------------------
wait_for_port() {
    local port=\$1
    local name=\$2
    local max_wait=\$3
    local elapsed=0
    while ! curl -s --connect-timeout 2 "http://127.0.0.1:\${port}" >/dev/null 2>&1; do
        sleep 2
        elapsed=\$((elapsed + 2))
        if [ \$elapsed -ge \$max_wait ]; then
            echo -e "  \${RED}✗ \${name} did not respond within \${max_wait}s\${NC}"
            return 1
        fi
        echo -e "  \${YELLOW}⏳ Waiting for \${name} (\${elapsed}s)...\${NC}"
    done
    echo -e "  \${GREEN}✓ \${name} is up on port \${port}\${NC}"
    return 0
}

# --------------------------------------------------------------------------
# 1. OLLAMA — Embedding-only
# --------------------------------------------------------------------------
echo -e "\${BOLD}[1/3] Ollama (Embeddings for AgentMemory)\${NC}"

if curl -s --connect-timeout 2 http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then
    echo -e "  \${GREEN}✓ Ollama already running\${NC}"
else
    echo -e "  \${YELLOW}→ Starting Ollama...\${NC}"
    if command -v ollama &>/dev/null; then
        ollama serve &>/dev/null &
        disown
    else
        echo -e "  \${RED}✗ Ollama not found. Install: brew install ollama\${NC}"
    fi
    wait_for_port 11434 "Ollama" 30 || true
fi

# Verify nomic-embed-text (auto-pull if missing after reboot — common HD2 quirk)
MODELS=\$(curl -s http://127.0.0.1:11434/api/tags 2>/dev/null)
if echo "\$MODELS" | grep -q "nomic-embed-text"; then
    echo -e "  \${GREEN}✓ nomic-embed-text loaded\${NC}"
else
    echo -e "  \${YELLOW}→ Pulling nomic-embed-text (fast if blobs exist)...\${NC}"
    OLLAMA_MODELS="${OLLAMA_PATH}" ollama pull nomic-embed-text 2>&1 || \\
        echo -e "  \${RED}✗ Pull failed — AgentMemory will run BM25-only\${NC}"
fi
echo ""

# --------------------------------------------------------------------------
# 2. ANYTHINGLLM (JURIS)
# --------------------------------------------------------------------------
echo -e "\${BOLD}[2/3] AnythingLLM (JURIS)\${NC}"
if curl -s --connect-timeout 2 http://127.0.0.1:3001/api/health >/dev/null 2>&1; then
    echo -e "  \${GREEN}✓ Already running on port 3001\${NC}"
else
    echo -e "  \${YELLOW}→ Waiting for AnythingLLM Login Item...\${NC}"
    ALLM_WAIT=0
    while ! curl -s --connect-timeout 2 http://127.0.0.1:3001/api/health >/dev/null 2>&1; do
        sleep 3
        ALLM_WAIT=\$((ALLM_WAIT + 3))
        if [ \$ALLM_WAIT -ge 90 ]; then
            echo -e "  \${RED}✗ AnythingLLM didn't start in 90s. Run: open -a AnythingLLM\${NC}"
            break
        fi
        echo -e "  \${YELLOW}⏳ Waiting (\${ALLM_WAIT}s/90s)...\${NC}"
    done
    if curl -s --connect-timeout 2 http://127.0.0.1:3001/api/health >/dev/null 2>&1; then
        echo -e "  \${GREEN}✓ AnythingLLM up\${NC}"
    fi
fi
echo ""

# --------------------------------------------------------------------------
# 3. AGENTMEMORY — with binary store backup BEFORE startup
# --------------------------------------------------------------------------
echo -e "\${BOLD}[3/3] AgentMemory (MEMORY)\${NC}"

# SAFETY: back up the binary store BEFORE AgentMemory starts.
# Keeps the 5 most recent snapshots — recovery from a bad start.
BIN_STORE="\$HOME/data/state_store.db/mem%3Amemories.bin"
BACKUP_DIR="\$HOME/data/memory_backups"
mkdir -p "\$BACKUP_DIR" 2>/dev/null
if [ -f "\$BIN_STORE" ] && [ -s "\$BIN_STORE" ]; then
    FSIZE=\$(stat -f%z "\$BIN_STORE" 2>/dev/null || echo "0")
    if [ "\$FSIZE" -gt 10000 ]; then
        cp "\$BIN_STORE" "\$BACKUP_DIR/memories_\$(date +%Y%m%d_%H%M%S).bin"
        ls -t "\$BACKUP_DIR"/memories_*.bin 2>/dev/null | tail -n +6 | xargs rm -f 2>/dev/null
        echo -e "  \${GREEN}✓ Binary store backed up (\$(( FSIZE / 1024 ))KB) — 5 most recent kept\${NC}"
    fi
fi

if curl -s --connect-timeout 2 http://127.0.0.1:3111/agentmemory/health >/dev/null 2>&1; then
    echo -e "  \${GREEN}✓ Already running on port 3111\${NC}"
else
    echo -e "  \${YELLOW}→ Starting AgentMemory...\${NC}"
    pushd "\$HOME" >/dev/null
    if command -v agentmemory &>/dev/null; then
        agentmemory &>/dev/null &
        disown
    else
        npx @agentmemory/agentmemory &>/dev/null &
        disown
    fi
    popd >/dev/null
    wait_for_port 3111 "AgentMemory" 45
fi

# Health check
HEALTH=\$(curl -s http://127.0.0.1:3111/agentmemory/health 2>/dev/null)
if [ -n "\$HEALTH" ]; then
    echo -e "  \${GREEN}✓ Health check passed — Viewer: http://localhost:3113\${NC}"
fi
echo ""

# --------------------------------------------------------------------------
# STATUS SUMMARY
# --------------------------------------------------------------------------
echo -e "\${CYAN}╔══════════════════════════════════════════════════════╗\${NC}"
echo -e "\${CYAN}║\${NC}  \${BOLD}${ENGINE_TITLE^^} STATUS\${NC}"
echo -e "\${CYAN}╠══════════════════════════════════════════════════════╣\${NC}"
curl -s --connect-timeout 2 http://127.0.0.1:11434/api/tags >/dev/null 2>&1 && \\
    echo -e "\${CYAN}║\${NC}  \${GREEN}✓\${NC} Ollama         port 11434" || \\
    echo -e "\${CYAN}║\${NC}  \${RED}✗\${NC} Ollama         NOT RUNNING"
curl -s --connect-timeout 2 http://127.0.0.1:3001/api/health >/dev/null 2>&1 && \\
    echo -e "\${CYAN}║\${NC}  \${GREEN}✓\${NC} JURIS          port 3001" || \\
    echo -e "\${CYAN}║\${NC}  \${RED}✗\${NC} JURIS          NOT RUNNING"
curl -s --connect-timeout 2 http://127.0.0.1:3111/agentmemory/health >/dev/null 2>&1 && \\
    echo -e "\${CYAN}║\${NC}  \${GREEN}✓\${NC} MEMORY         port 3111" || \\
    echo -e "\${CYAN}║\${NC}  \${RED}✗\${NC} MEMORY         NOT RUNNING"
echo -e "\${CYAN}╚══════════════════════════════════════════════════════╝\${NC}"
echo ""
echo -e "\${GREEN}All systems go. Ready for Cowork.\${NC}"
echo ""
EOF

chmod +x "$LAUNCH_FILE"
echo -e "  ${GREEN}✓ Wrote $LAUNCH_FILE${NC}"

# --------------------------------------------------------------------------
# Wrapper .command file (this is what becomes the macOS Login Item)
# --------------------------------------------------------------------------
cat > "$WRAPPER_FILE" <<EOF
#!/bin/bash
# ${ENGINE_TITLE}Launcher — Login Item wrapper
# This .command file is what macOS opens at login. It launches Terminal
# and runs the actual boot script.
bash ~/Documents/launch_${ENGINE_LOWER}.sh
EOF
chmod +x "$WRAPPER_FILE"
echo -e "  ${GREEN}✓ Wrote $WRAPPER_FILE${NC}"
echo ""

# --------------------------------------------------------------------------
# 4. INSTRUCTIONS FOR ADDING TO LOGIN ITEMS
# --------------------------------------------------------------------------
echo -e "${BOLD}[4/4] Add to Login Items (manual — macOS UI step)${NC}"
echo ""
echo -e "  ${CYAN}1.${NC} Open ${BOLD}System Settings${NC}"
echo -e "  ${CYAN}2.${NC} Go to ${BOLD}General → Login Items${NC}"
echo -e "  ${CYAN}3.${NC} Click ${BOLD}+${NC} under 'Open at Login'"
echo -e "  ${CYAN}4.${NC} Navigate to ${BOLD}~/Documents/${NC} and pick:"
echo -e "       ${YELLOW}${ENGINE_TITLE}Launcher.command${NC}"
echo -e "  ${CYAN}5.${NC} ${BOLD}Also add AnythingLLM${NC} as a separate Login Item if you haven't"
echo -e "       (since AnythingLLM Desktop launches itself — your launcher waits for it)"
echo ""
echo -e "  ${CYAN}Test it now without rebooting:${NC}"
echo -e "  ${YELLOW}    open $WRAPPER_FILE${NC}"
echo ""

# --------------------------------------------------------------------------
# DONE
# --------------------------------------------------------------------------
echo -e "${CYAN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}  ${BOLD}STEP 07 COMPLETE${NC}                                    ${CYAN}║${NC}"
echo -e "${CYAN}╠══════════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║${NC}  Engine name:    $ENGINE_TITLE"
echo -e "${CYAN}║${NC}  Launch script:  ~/Documents/launch_${ENGINE_LOWER}.sh"
echo -e "${CYAN}║${NC}  Login wrapper:  ~/Documents/${ENGINE_TITLE}Launcher.command"
echo -e "${CYAN}║${NC}  Ollama models:  $OLLAMA_PATH"
echo -e "${CYAN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Next: open ~/Documents/TRIBE_JURIS_KIT/08_library_load.md"
echo ""
